# Pandas basics

Can we see `countries.csv` and `continent_facts.csv`? Let's check with `ls`.

> The `!` allows you to run command line commands in a notebook

In [6]:
!ls

01-pandas basics.ipynb continent_facts.csv
Do Now.ipynb           countries.csv

If you don't see `countries.csv` etc, find out where the notebook is with `pwd` and move those files to that location.

In [2]:
!pwd

/Users/soma/Library/CloudStorage/Dropbox/Soma/Curriculum/2024-lede/06-pandas-git-github/06-classwork-inclass

## Let's install pandas!

`--quiet` makes things quiet, the opposite of quiet is... "verbose" is the word you're looking for if you want EVEN MORE details

`pip install` you only run once, it goes out on the internet and downloads pandas and then installs it somewhere on your computer.

In [11]:
!pip install --quiet pandas

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: pip install --upgrade pip

`import` says "I installed this on my computer somewhere, bring it into this file/notebook/whatever so I can use it here"

In [12]:
# This means "I want to use requests in this notebook/file"
import requests

If you get ModuleNotFound for `pandas` after using `!pip install` it's because your Python on the command line is NOT the same Python as your Jupyter Python. We *could* fix it permanently, or for now, you could just use `%pip install pandas` instead.

In [18]:
import pandas as pd

In [107]:
# Use pd to read in the csv "countries.csv"
# this is called a dataframe
df = pd.read_csv("countries.csv")
# Let's look at the first five
df.head()

               country   continent  life_expectancy  population           gdp
0          Afghanistan        Asia           54.863    22856302   15153728226
1              Albania      Europe           74.200     3071856   12886435920
2              Algeria      Africa           68.963    30533827  155661450046
3               Angola      Africa           45.234    13926373   34063908358
4  Antigua and Barbuda  N. America           73.544       77656     989182128

In [108]:
# Show me the last five rows
# two approaches:
# guess what the opposite of .head() is
# use tab

In [109]:
df.tail()

                country continent  life_expectancy  population           gdp
183             Vietnam      Asia           73.777    78758010  124201381770
184  West Bank and Gaza      Asia           70.929     3198560   24264276160
185         Yemen, Rep.      Asia           60.404    17723186   39292303362
186              Zambia    Africa           41.802    10201562   10558616670
187            Zimbabwe    Africa           43.976    12509477    9319560365

In [110]:
# What is last() for?
# hold down shift + tab to get help documentation
# df.last

In [111]:
# If you want the first three columns
df.head()

               country   continent  life_expectancy  population           gdp
0          Afghanistan        Asia           54.863    22856302   15153728226
1              Albania      Europe           74.200     3071856   12886435920
2              Algeria      Africa           68.963    30533827  155661450046
3               Angola      Africa           45.234    13926373   34063908358
4  Antigua and Barbuda  N. America           73.544       77656     989182128

**Above** it's pretty, it's a dataframe

**Below** it's ugly, it's just one column, it's a Series

In [112]:
# Try to guess how to get the life expectancy of 
# every! single! country!
# I promise it's easy and it's what you hope it is
df['life_expectancy']

0      54.863
1      74.200
2      68.963
3      45.234
4      73.544
        ...
183    73.777
184    70.929
185    60.404
186    41.802
187    43.976
Name: life_expectancy, Length: 188, dtype: float64

In [113]:
# hey pandas!
# give me a dataframe
# give me the life expectancy column
df['life_expectancy']

0      54.863
1      74.200
2      68.963
3      45.234
4      73.544
        ...
183    73.777
184    70.929
185    60.404
186    41.802
187    43.976
Name: life_expectancy, Length: 188, dtype: float64

In [114]:
df.sort_values('life_expectancy')

,country,continent,life_expectancy,population,gdp
147,Sierra Leone,Africa,38.123,4143115,2141990455
186,Zambia,Africa,41.802,10201562,10558616670
31,Central African Rep.,Africa,43.727,3701607,2820624534
187,Zimbabwe,Africa,43.976,12509477,9319560365
3,Angola,Africa,45.234,13926373,34063908358
...,...,...,...,...,...
160,Sweden,Europe,79.840,8860153,253754781920
7,Australia,Oceania,79.930,19164351,560384787591
161,Switzerland,Europe,79.990,7167908,246475684488
72,"Hong Kong, China",Asia,80.361,6783317,203309577124
83,Japan,Asia,81.350,125720310,3590446333290

In [115]:
df.sort_values('life_expectancy', ascending=False)

,country,continent,life_expectancy,population,gdp
83,Japan,Asia,81.350,125720310,3590446333290
72,"Hong Kong, China",Asia,80.361,6783317,203309577124
161,Switzerland,Europe,79.990,7167908,246475684488
7,Australia,Oceania,79.930,19164351,560384787591
160,Sweden,Europe,79.840,8860153,253754781920
...,...,...,...,...,...
3,Angola,Africa,45.234,13926373,34063908358
187,Zimbabwe,Africa,43.976,12509477,9319560365
31,Central African Rep.,Africa,43.727,3701607,2820624534
186,Zambia,Africa,41.802,10201562,10558616670
147,Sierra Leone,Africa,38.123,4143115,2141990455

In [116]:
df[['country', 'life_expectancy']]

                 country  life_expectancy
0            Afghanistan           54.863
1                Albania           74.200
2                Algeria           68.963
3                 Angola           45.234
4    Antigua and Barbuda           73.544
..                   ...              ...
183              Vietnam           73.777
184   West Bank and Gaza           70.929
185          Yemen, Rep.           60.404
186               Zambia           41.802
187             Zimbabwe           43.976

[188 rows x 2 columns]

In [117]:
df.sort_values('life_expectancy', ascending=False).head(10)

              country   continent  life_expectancy  population            gdp
83              Japan        Asia           81.350   125720310  3590446333290
72   Hong Kong, China        Asia           80.361     6783317   203309577124
161       Switzerland      Europe           79.990     7167908   246475684488
7           Australia     Oceania           79.930    19164351   560384787591
160            Sweden      Europe           79.840     8860153   253754781920
81              Italy      Europe           79.730    56986329  1547748695640
74            Iceland      Europe           79.720      281210     8743381320
29             Canada  N. America           79.410    30667365   995094659520
155             Spain      Europe           79.340    40288457   943152778370
57             France      Europe           79.230    59047795  1690892657620

In [118]:
# never use inplace=True

In [119]:
# Can I udo .head().tail()
# df -> Give me the dataframe
# .head() -> give me the first five (of the datframe)
# .tail() -> give me the last five (of the first five)
df.head().tail()

               country   continent  life_expectancy  population           gdp
0          Afghanistan        Asia           54.863    22856302   15153728226
1              Albania      Europe           74.200     3071856   12886435920
2              Algeria      Africa           68.963    30533827  155661450046
3               Angola      Africa           45.234    13926373   34063908358
4  Antigua and Barbuda  N. America           73.544       77656     989182128

In [120]:
# sort everything in the dataframe by life expectancy
# then give me the first ten
df.sort_values('life_expectancy', ascending=False).head(10)

# give me the first ten rows
# then sort them by life expectancy
df.head(10).sort_values('life_expectancy', ascending=False)

               country   continent  life_expectancy  population           gdp
7            Australia     Oceania           79.930    19164351  560384787591
8              Austria      Europe           78.330     8004712  256214821696
1              Albania      Europe           74.200     3071856   12886435920
5            Argentina  S. America           73.822    36930709  390394524839
4  Antigua and Barbuda  N. America           73.544       77656     989182128
6              Armenia      Europe           71.494     3076098    6502871172
2              Algeria      Africa           68.963    30533827  155661450046
9           Azerbaijan      Europe           66.851     8110723   20544461359
0          Afghanistan        Asia           54.863    22856302   15153728226
3               Angola      Africa           45.234    13926373   34063908358

In [121]:
# give me the row with the index of 2
df.loc[2]

country                 Algeria
continent                Africa
life_expectancy          68.963
population             30533827
gdp                155661450046
Name: 2, dtype: object

In [122]:
df['continent']

0            Asia
1          Europe
2          Africa
3          Africa
4      N. America
          ...
183          Asia
184          Asia
185          Asia
186        Africa
187        Africa
Name: continent, Length: 188, dtype: object

In [123]:
df[df['life_expectancy'] > 80]

             country continent  life_expectancy  population            gdp
72  Hong Kong, China      Asia           80.361     6783317   203309577124
83             Japan      Asia           81.350   125720310  3590446333290

In [124]:
# Entry country in Asia with a life expectancy over 75
# df['life_expectancy'] > 75
# df['continent'] == 'Asia'

# df['life_expectancy'] > 75 and df['continent'] == 'Asia'
# we have to do this, sadly :(
# (df['life_expectancy'] > 75) & (df['continent'] == 'Asia')
df[(df['life_expectancy'] > 75) & (df['continent'] == 'Asia')]

              country continent  life_expectancy  population            gdp
23             Brunei      Asia           75.927      327036    15704268720
72   Hong Kong, China      Asia           80.361     6783317   203309577124
80             Israel      Asia           78.750     6014953   137345436802
83              Japan      Asia           81.350   125720310  3590446333290
89        Korea, Rep.      Asia           76.114    45987624   781559669880
100      Macao, China      Asia           77.627      431867     9722189904
135             Qatar      Asia           76.680      590957    35690257058
148         Singapore      Asia           78.340     3919300   144363496200
163            Taiwan      Asia           76.020    22183000   521855075000

In [125]:
# This seems easier to read to me???? but no one does it :(
df.query('life_expectancy > 75 and continent == "Asia"')

              country continent  life_expectancy  population            gdp
23             Brunei      Asia           75.927      327036    15704268720
72   Hong Kong, China      Asia           80.361     6783317   203309577124
80             Israel      Asia           78.750     6014953   137345436802
83              Japan      Asia           81.350   125720310  3590446333290
89        Korea, Rep.      Asia           76.114    45987624   781559669880
100      Macao, China      Asia           77.627      431867     9722189904
135             Qatar      Asia           76.680      590957    35690257058
148         Singapore      Asia           78.340     3919300   144363496200
163            Taiwan      Asia           76.020    22183000   521855075000

In [126]:
df[df['country'] == 'Mexico']

    country   continent  life_expectancy  population            gdp
110  Mexico  N. America            74.38    99959594  1088959817036

In [127]:
# Filter for everything that is in Asia
# df['continent'] == 'Asia'
df[df['continent'] == 'Asia']

,country,continent,life_expectancy,population,gdp
0,Afghanistan,Asia,54.863,22856302,15153728226
11,Bahrain,Asia,74.497,638193,14049818895
12,Bangladesh,Asia,65.309,129592275,139311695625
18,Bhutan,Asia,60.307,571262,1669227564
23,Brunei,Asia,75.927,327036,15704268720
27,Cambodia,Asia,62.030,12446949,12222903918
34,China,Asia,72.124,1269116737,4323880722959
72,"Hong Kong, China",Asia,80.361,6783317,203309577124
75,India,Asia,62.129,1053898107,1736824080336
76,Indonesia,Asia,67.289,213395411,579155145454
77,Iran,Asia,69.611,65342319,561943943400
78,Iraq,Asia,70.845,23857458,94260816558
80,Israel,Asia,78.750,6014953,137345436802
83,Japan,Asia,81.350,125720310,3590446333290
84,Jordan,Asia,71.724,4827096,17686479744
85,Kazakhstan,Asia,63.513,14956694,80257620004
88,"Korea, Dem. Rep.",Asia,65.271,22894095,38668126455
89,"Korea, Rep.",Asia,76.114,45987624,781559669880
90,Kuwait,Asia,73.133,1940786,70638788042
91,Kyrgyzstan,Asia,66.232,4954850,7566055950
92,Laos,Asia,61.689,5317060,8071297080
94,Lebanon,Asia,74.409,3742329,21686796555
100,"Macao, China",Asia,77.627,431867,9722189904
104,Malaysia,Asia,72.810,23414909,237918890349
105,Maldives,Asia,69.279,273236,938019188
113,Mongolia,Asia,62.876,2411369,4863731273
117,Myanmar,Asia,62.073,44957660,46486220440
119,Nepal,Asia,62.055,24400606,25718238724
126,Oman,Asia,72.139,2264163,43480986252
127,Pakistan,Asia,63.854,144522192,301473292512
132,Philippines,Asia,66.774,77309965,200851289070
135,Qatar,Asia,76.680,590957,35690257058
137,Russia,Asia,65.380,146757517,1257711920690
143,Saudi Arabia,Asia,72.401,20045276,400925565276
148,Singapore,Asia,78.340,3919300,144363496200
156,Sri Lanka,Asia,71.078,18745084,56179016748
162,Syria,Asia,73.316,15988534,62914881290
163,Taiwan,Asia,76.020,22183000,521855075000
164,Tajikistan,Asia,63.570,6172807,6178979807
166,Thailand,Asia,70.921,63155029,352278751762
167,Timor-Leste,Asia,59.468,830089,2276934127
172,Turkey,Asia,70.010,63627862,432860345186
173,Turkmenistan,Asia,63.925,4501419,14805167091
176,United Arab Emirates,Asia,74.163,3033491,91041131892
180,Uzbekistan,Asia,66.999,24775610,40508122350
183,Vietnam,Asia,73.777,78758010,124201381770
184,West Bank and Gaza,Asia,70.929,3198560,24264276160
185,"Yemen, Rep.",Asia,60.404,17723186,39292303362

In [128]:
df.sort_values('life_expectancy', ascending=False) \
    .head(10) \
    [['country', 'life_expectancy']]

              country  life_expectancy
83              Japan           81.350
72   Hong Kong, China           80.361
161       Switzerland           79.990
7           Australia           79.930
160            Sweden           79.840
81              Italy           79.730
74            Iceland           79.720
29             Canada           79.410
155             Spain           79.340
57             France           79.230

In [129]:
(
    df.sort_values('life_expectancy', ascending=False)
        .head(10)[['country', 'life_expectancy']]
)

              country  life_expectancy
83              Japan           81.350
72   Hong Kong, China           80.361
161       Switzerland           79.990
7           Australia           79.930
160            Sweden           79.840
81              Italy           79.730
74            Iceland           79.720
29             Canada           79.410
155             Spain           79.340
57             France           79.230

In [130]:
# .average?
# .avg?
# .....?
df['life_expectancy'].mean()

66.50153603526596

In [131]:
# Complain complain complain, mean is easily skewed by outliers
# I want a better measure of central tendencies
df['life_expectancy'].median()

70.04150000000001

In [132]:
df['life_expectancy'].describe()

count    188.000000
mean      66.501536
std       10.298458
min       38.123000
25%       59.663750
50%       70.041500
75%       74.134500
max       81.350000
Name: life_expectancy, dtype: float64

In [133]:
df['gdp'].sum()

48316204002444

In [134]:
df.head(2)

       country continent  life_expectancy  population          gdp
0  Afghanistan      Asia           54.863    22856302  15153728226
1      Albania    Europe           74.200     3071856  12886435920

In [135]:
df[['life_expectancy', 'gdp']].corr()

                 life_expectancy       gdp
life_expectancy         1.000000  0.209858
gdp                     0.209858  1.000000

In [136]:
# calculate the per capita gdp, gdp per capita
# gdp / population
df['gdp'] / df['population']

0        663.0
1       4195.0
2       5098.0
3       2446.0
4      12738.0
        ...
183     1577.0
184     7586.0
185     2217.0
186     1035.0
187      745.0
Length: 188, dtype: float64

In [137]:
# Try to save this as a column??????
df['gdp_per_capita'] = df['gdp'] / df['population']
df.head(2)

,country,continent,life_expectancy,population,gdp,gdp_per_capita
0,Afghanistan,Asia,54.863,22856302,15153728226,663.0
1,Albania,Europe,74.200,3071856,12886435920,4195.0

In [138]:
# Step 1: df
# Step 2: filters
# Step 3: groupby
# Step 4: column(s)
# Step 5: the math

df.groupby('continent')['life_expectancy'].median()

continent
Africa        52.1025
Asia          70.4275
Europe        75.5800
N. America    70.5765
Oceania       67.4955
S. America    70.7660
Name: life_expectancy, dtype: float64

In [139]:
5 * 5

25

In [140]:
df.head()

,country,continent,life_expectancy,population,gdp,gdp_per_capita
0,Afghanistan,Asia,54.863,22856302,15153728226,663.0
1,Albania,Europe,74.200,3071856,12886435920,4195.0
2,Algeria,Africa,68.963,30533827,155661450046,5098.0
3,Angola,Africa,45.234,13926373,34063908358,2446.0
4,Antigua and Barbuda,N. America,73.544,77656,989182128,12738.0

In [141]:
south_america_df = df[df['continent'] == 'S. America']
south_america_df.head(2)

,country,continent,life_expectancy,population,gdp,gdp_per_capita
5,Argentina,S. America,73.822,36930709,390394524839,10571.0
19,Bolivia,S. America,62.994,8307248,28194799712,3394.0

In [142]:
south_america_df['population'] = 0

/var/folders/25/h3prywj14qb0mlkl2s8bxq5m0000gn/T/ipykernel_12859/756261850.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  south_america_df['population'] = 0

In [143]:
south_america_df

,country,continent,life_expectancy,population,gdp,gdp_per_capita
5,Argentina,S. America,73.822,0,390394524839,10571.0
19,Bolivia,S. America,62.994,0,28194799712,3394.0
22,Brazil,S. America,70.261,0,1405170917672,8056.0
33,Chile,S. America,77.010,0,160905821700,10435.0
35,Colombia,S. America,71.026,0,228604190334,5749.0
48,Ecuador,S. America,73.353,0,69329649168,5616.0
69,Guyana,S. America,63.290,0,2302670241,3141.0
130,Paraguay,S. America,70.073,0,20877206873,3907.0
131,Peru,S. America,70.506,0,149766187617,5791.0
158,Suriname,S. America,67.851,0,2650284742,5677.0
179,Uruguay,S. America,74.777,0,30176948072,9092.0
182,Venezuela,S. America,72.432,0,229701899936,9434.0

In [144]:
# df[df['continent'] == 'S. America']

In [145]:
df[df['continent'] == 'S. America']

,country,continent,life_expectancy,population,gdp,gdp_per_capita
5,Argentina,S. America,73.822,36930709,390394524839,10571.0
19,Bolivia,S. America,62.994,8307248,28194799712,3394.0
22,Brazil,S. America,70.261,174425387,1405170917672,8056.0
33,Chile,S. America,77.010,15419820,160905821700,10435.0
35,Colombia,S. America,71.026,39764166,228604190334,5749.0
48,Ecuador,S. America,73.353,12345023,69329649168,5616.0
69,Guyana,S. America,63.290,733101,2302670241,3141.0
130,Paraguay,S. America,70.073,5343539,20877206873,3907.0
131,Peru,S. America,70.506,25861887,149766187617,5791.0
158,Suriname,S. America,67.851,466846,2650284742,5677.0
179,Uruguay,S. America,74.777,3319066,30176948072,9092.0
182,Venezuela,S. America,72.432,24348304,229701899936,9434.0

In [151]:
df['continent'].value_counts()

continent
Africa        54
Asia          48
Europe        42
N. America    22
S. America    12
Oceania       10
Name: count, dtype: int64

In [148]:
df['continent'].describe()

count        188
unique         6
top       Africa
freq          54
Name: continent, dtype: object

In [152]:
df['continent'].nunique()

6

In [153]:
df['continent'].unique()

array(['Asia', 'Europe', 'Africa', 'N. America', 'S. America', 'Oceania'],
      dtype=object)

## Reading stuff from the internet???

In [ ]:
# ModuleNotFoundError lxml
%pip install lxml

In [16]:
import pandas as pd

url = "https://www.theguardian.com/football/laligafootball/table"
# Go onto the internet and look at that web page
# get all of the tables from it and save them in
# the variable tables
tables = pd.read_html(url)

# and now we'll count the number of tables you found
len(tables)

1

In [24]:
df = tables[0]
df.head()

,P,Team,GP,W,D,L,F,A,GD,Pts,Form
0,1,Real Madrid,38,29,8,1,87,26,61,95,Won 3-0 against Cadiz Won 4-0 against Granada...
1,2,Barcelona,38,26,7,5,79,44,35,85,Lost 2-4 to Girona Won 2-0 against Real Socie...
2,3,Girona,38,25,6,7,85,46,39,81,Won 4-2 against Barcelona Drew 2-2 with Alave...
3,4,Atlético,38,24,4,10,70,43,27,76,Won 1-0 against Mallorca Won 1-0 against Celt...
4,5,A Bilbao,38,19,11,8,61,37,24,68,Won 2-0 against Getafe Drew 2-2 with Osasuna ...

In [25]:
df.head()

,P,Team,GP,W,D,L,F,A,GD,Pts,Form
0,1,Real Madrid,38,29,8,1,87,26,61,95,Won 3-0 against Cadiz Won 4-0 against Granada...
1,2,Barcelona,38,26,7,5,79,44,35,85,Lost 2-4 to Girona Won 2-0 against Real Socie...
2,3,Girona,38,25,6,7,85,46,39,81,Won 4-2 against Barcelona Drew 2-2 with Alave...
3,4,Atlético,38,24,4,10,70,43,27,76,Won 1-0 against Mallorca Won 1-0 against Celt...
4,5,A Bilbao,38,19,11,8,61,37,24,68,Won 2-0 against Getafe Drew 2-2 with Osasuna ...

In [27]:
# Always index=False
df.to_csv("teams.csv", index=False)

In [23]:
# pd.read_csv("teams.csv")

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,P,Team,GP,W,D,L,F,A,GD,Pts,Form
0,0,0,0,0,0,1,Real Madrid,38,29,8,1,87,26,61,95,Won 3-0 against Cadiz Won 4-0 against Granada...
1,1,1,1,1,1,2,Barcelona,38,26,7,5,79,44,35,85,Lost 2-4 to Girona Won 2-0 against Real Socie...
2,2,2,2,2,2,3,Girona,38,25,6,7,85,46,39,81,Won 4-2 against Barcelona Drew 2-2 with Alave...
3,3,3,3,3,3,4,Atlético,38,24,4,10,70,43,27,76,Won 1-0 against Mallorca Won 1-0 against Celt...
4,4,4,4,4,4,5,A Bilbao,38,19,11,8,61,37,24,68,Won 2-0 against Getafe Drew 2-2 with Osasuna ...
5,5,5,5,5,5,6,Real Sociedad,38,16,12,10,51,39,12,60,Won 2-0 against Las Palmas Lost 0-2 to Barcel...
6,6,6,6,6,6,7,Real Betis,38,14,15,9,48,45,3,57,Won 2-0 against Osasuna Won 3-2 against Almer...
7,7,7,7,7,7,8,Villarreal,38,14,11,13,65,65,0,53,Lost 2-3 to Celta Vigo Won 3-2 against Sevill...
8,8,8,8,8,8,9,Valencia,38,13,10,15,40,45,-5,49,Lost 0-1 to Alaves Drew 0-0 with Rayo Valleca...
9,9,9,9,9,9,10,Alaves,38,12,10,16,36,46,-10,46,Won 1-0 against Valencia Drew 2-2 with Girona...
10,10,10,10,10,10,11,Osasuna,38,12,9,17,45,56,-11,45,Lost 0-2 to Real Betis Drew 2-2 with A Bilbao...
11,11,11,11,11,11,12,Getafe,38,10,13,15,42,54,-12,43,Lost 0-2 to A Bilbao Lost 0-1 to Cadiz Lost ...
12,12,12,12,12,12,13,Celta Vigo,38,10,11,17,46,57,-11,41,Won 3-2 against Villarreal Lost 0-1 to Atléti...
13,13,13,13,13,13,14,Sevilla,38,10,11,17,48,54,-6,41,Won 3-0 against Granada Lost 2-3 to Villarrea...
14,14,14,14,14,14,15,Mallorca,38,8,16,14,33,44,-11,40,Lost 0-1 to Atlético Won 1-0 against Las Palm...
15,15,15,15,15,15,16,Las Palmas,38,10,10,18,33,47,-14,40,Lost 0-2 to Real Sociedad Lost 0-1 to Mallorc...
16,16,16,16,16,16,17,Rayo Vallecano,38,8,14,16,29,48,-19,38,Lost 0-1 to Almeria Drew 0-0 with Valencia W...
17,17,17,17,17,17,18,Cadiz,38,6,15,17,26,55,-29,33,Lost 0-3 to Real Madrid Won 1-0 against Getaf...
18,18,18,18,18,18,19,Almeria,38,3,12,23,43,75,-32,21,Won 1-0 against Rayo Vallecano Lost 2-3 to Re...
19,19,19,19,19,19,20,Granada,38,4,9,25,38,79,-41,21,Lost 0-3 to Sevilla Lost 0-4 to Real Madrid ...

In [8]:
# tables = pd.read_html("http://www.bigpumpkins.com/WeighoffResultsGPC.aspx?c=L&y=2023")
# len(tables)

4

In [10]:
# tables[0].tail()

,Place,Weight (lbs),Grower Name,City,State/Prov,Country,GPC Site,Seed (Mother),Pollinator (Father),OTT,Est. Weight,Pct. Chart
261,NaN,This page shows the GPC results for the select...,This page shows the GPC results for the select...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,NaN,PlaceWeight (lbs)Grower NameCityState/ProvCoun...,PlaceWeight (lbs)Grower NameCityState/ProvCoun...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
264,Top of Page Questions or comments? Send mail t...,Top of Page Questions or comments? Send mail t...,Top of Page Questions or comments? Send mail t...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,"259 Entries. (17 exhibition only, 4 damaged)","259 Entries. (17 exhibition only, 4 damaged)","259 Entries. (17 exhibition only, 4 damaged)","259 Entries. (17 exhibition only, 4 damaged)","259 Entries. (17 exhibition only, 4 damaged)","259 Entries. (17 exhibition only, 4 damaged)","259 Entries. (17 exhibition only, 4 damaged)","259 Entries. (17 exhibition only, 4 damaged)","259 Entries. (17 exhibition only, 4 damaged)","259 Entries. (17 exhibition only, 4 damaged)","259 Entries. (17 exhibition only, 4 damaged)","259 Entries. (17 exhibition only, 4 damaged)"

## API stuff??? JSON stuff???

In [28]:
import requests

url = "http://api.weatherapi.com/v1/forecast.json?key=1deea713c0524e4abd621042220711&q=London&days=3&aqi=yes&alerts=no"
response = requests.get(url)
data = response.json()

In [30]:
data.keys()

dict_keys(['location', 'current', 'forecast'])

In [32]:
data['forecast']['forecastday']

[{'date': '2024-06-12',
  'date_epoch': 1718150400,
  'day': {'maxtemp_c': 15.9,
   'maxtemp_f': 60.7,
   'mintemp_c': 7.7,
   'mintemp_f': 45.8,
   'avgtemp_c': 12.3,
   'avgtemp_f': 54.1,
   'maxwind_mph': 7.4,
   'maxwind_kph': 11.9,
   'totalprecip_mm': 1.54,
   'totalprecip_in': 0.06,
   'totalsnow_cm': 0.0,
   'avgvis_km': 9.1,
   'avgvis_miles': 5.0,
   'avghumidity': 71,
   'daily_will_it_rain': 1,
   'daily_chance_of_rain': 87,
   'daily_will_it_snow': 0,
   'daily_chance_of_snow': 0,
   'condition': {'text': 'Patchy rain nearby',
    'icon': '//cdn.weatherapi.com/weather/64x64/day/176.png',
    'code': 1063},
   'uv': 3.0},
  'astro': {'sunrise': '04:43 AM',
   'sunset': '09:18 PM',
   'moonrise': '10:45 AM',
   'moonset': '01:03 AM',
   'moon_phase': 'Waxing Crescent',
   'moon_illumination': 29,
   'is_moon_up': 1,
   'is_sun_up': 0},
  'hour': [{'time_epoch': 1718146800,
    'time': '2024-06-12 00:00',
    'temp_c': 8.7,
    'temp_f': 47.7,
    'is_day': 0,
    'condition': {'text': 'Overcast ',
     'icon': '//cdn.weatherapi.com/weather/64x64/night/122.png',
     'code': 1009},
    'wind_mph': 3.4,
    'wind_kph': 5.4,
    'wind_degree': 24,
    'wind_dir': 'NNE',
    'pressure_mb': 1021.0,
    'pressure_in': 30.16,
    'precip_mm': 0.0,
    'precip_in': 0.0,
    'snow_cm': 0.0,
    'humidity': 93,
    'cloud': 91,
    'feelslike_c': 8.2,
    'feelslike_f': 46.8,
    'windchill_c': 8.2,
    'windchill_f': 46.8,
    'heatindex_c': 8.7,
    'heatindex_f': 47.7,
    'dewpoint_c': 7.7,
    'dewpoint_f': 45.9,
    'will_it_rain': 0,
    'chance_of_rain': 0,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 5.9,
    'gust_kph': 9.5,
    'uv': 1.0},
   {'time_epoch': 1718150400,
    'time': '2024-06-12 01:00',
    'temp_c': 8.2,
    'temp_f': 46.8,
    'is_day': 0,
    'condition': {'text': 'Clear ',
     'icon': '//cdn.weatherapi.com/weather/64x64/night/113.png',
     'code': 1000},
    'wind_mph': 3.1,
    'wind_kph': 5.0,
    'wind_degree': 31,
    'wind_dir': 'NNE',
    'pressure_mb': 1021.0,
    'pressure_in': 30.16,
    'precip_mm': 0.0,
    'precip_in': 0.0,
    'snow_cm': 0.0,
    'humidity': 94,
    'cloud': 24,
    'feelslike_c': 7.8,
    'feelslike_f': 46.0,
    'windchill_c': 7.8,
    'windchill_f': 46.0,
    'heatindex_c': 8.2,
    'heatindex_f': 46.8,
    'dewpoint_c': 7.3,
    'dewpoint_f': 45.1,
    'will_it_rain': 0,
    'chance_of_rain': 0,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 5.5,
    'gust_kph': 8.9,
    'uv': 1.0},
   {'time_epoch': 1718154000,
    'time': '2024-06-12 02:00',
    'temp_c': 7.9,
    'temp_f': 46.3,
    'is_day': 0,
    'condition': {'text': 'Clear ',
     'icon': '//cdn.weatherapi.com/weather/64x64/night/113.png',
     'code': 1000},
    'wind_mph': 2.5,
    'wind_kph': 4.0,
    'wind_degree': 33,
    'wind_dir': 'NNE',
    'pressure_mb': 1021.0,
    'pressure_in': 30.15,
    'precip_mm': 0.0,
    'precip_in': 0.0,
    'snow_cm': 0.0,
    'humidity': 94,
    'cloud': 23,
    'feelslike_c': 7.8,
    'feelslike_f': 46.0,
    'windchill_c': 7.8,
    'windchill_f': 46.0,
    'heatindex_c': 7.9,
    'heatindex_f': 46.3,
    'dewpoint_c': 7.0,
    'dewpoint_f': 44.6,
    'will_it_rain': 0,
    'chance_of_rain': 0,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 4.3,
    'gust_kph': 6.9,
    'uv': 1.0},
   {'time_epoch': 1718157600,
    'time': '2024-06-12 03:00',
    'temp_c': 7.9,
    'temp_f': 46.2,
    'is_day': 0,
    'condition': {'text': 'Mist',
     'icon': '//cdn.weatherapi.com/weather/64x64/night/143.png',
     'code': 1030},
    'wind_mph': 1.8,
    'wind_kph': 2.9,
    'wind_degree': 27,
    'wind_dir': 'NNE',
    'pressure_mb': 1021.0,
    'pressure_in': 30.16,
    'precip_mm': 0.0,
    'precip_in': 0.0,
    'snow_cm': 0.0,
    'humidity': 94,
    'cloud': 80,
    'feelslike_c': 7.9,
    'feelslike_f': 46.2,
    'windchill_c': 7.9,
    'windchill_f': 46.2,
    'heatindex_c': 7.9,
    'heatindex_f': 46.2,
    'dewpoint_c': 7.0,
    'dewpoint_f': 44.7,
    'will_it_rain': 0,
    'chance_of_rain': 0,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 2.0,
    'vis_miles': 1.0,
    'gust_mph': 3.3,
    'gust_kph': 5.3,
    'uv': 1.0},
   {'time_epoch': 1718161200,
    'time': '2024-06-12 04:00',
    'temp_c': 7.7,
    'temp_f': 45.8,
    'is_day': 0,
    'condition': {'text': 'Mist',
     'icon': '//cdn.weatherapi.com/weather/64x64/night/143.png',
     'code': 1030},
    'wind_mph': 1.6,
    'wind_kph': 2.5,
    'wind_degree': 32,
    'wind_dir': 'NNE',
    'pressure_mb': 1022.0,
    'pressure_in': 30.17,
    'precip_mm': 0.0,
    'precip_in': 0.0,
    'snow_cm': 0.0,
    'humidity': 94,
    'cloud': 37,
    'feelslike_c': 7.7,
    'feelslike_f': 45.8,
    'windchill_c': 7.7,
    'windchill_f': 45.8,
    'heatindex_c': 7.7,
    'heatindex_f': 45.8,
    'dewpoint_c': 6.9,
    'dewpoint_f': 44.3,
    'will_it_rain': 0,
    'chance_of_rain': 0,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 2.0,
    'vis_miles': 1.0,
    'gust_mph': 2.9,
    'gust_kph': 4.6,
    'uv': 1.0},
   {'time_epoch': 1718164800,
    'time': '2024-06-12 05:00',
    'temp_c': 8.5,
    'temp_f': 47.3,
    'is_day': 1,
    'condition': {'text': 'Partly Cloudy ',
     'icon': '//cdn.weatherapi.com/weather/64x64/day/116.png',
     'code': 1003},
    'wind_mph': 0.7,
    'wind_kph': 1.1,
    'wind_degree': 49,
    'wind_dir': 'NE',
    'pressure_mb': 1022.0,
    'pressure_in': 30.17,
    'precip_mm': 0.0,
    'precip_in': 0.0,
    'snow_cm': 0.0,
    'humidity': 93,
    'cloud': 36,
    'feelslike_c': 8.5,
    'feelslike_f': 47.3,
    'windchill_c': 8.5,
    'windchill_f': 47.3,
    'heatindex_c': 8.5,
    'heatindex_f': 47.3,
    'dewpoint_c': 7.4,
    'dewpoint_f': 45.3,
    'will_it_rain': 0,
    'chance_of_rain': 0,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 1.1,
    'gust_kph': 1.7,
    'uv': 3.0},
   {'time_epoch': 1718168400,
    'time': '2024-06-12 06:00',
    'temp_c': 9.6,
    'temp_f': 49.3,
    'is_day': 1,
    'condition': {'text': 'Patchy rain nearby',
     'icon': '//cdn.weatherapi.com/weather/64x64/day/176.png',
     'code': 1063},
    'wind_mph': 0.4,
    'wind_kph': 0.7,
    'wind_degree': 354,
    'wind_dir': 'N',
    'pressure_mb': 1022.0,
    'pressure_in': 30.18,
    'precip_mm': 0.03,
    'precip_in': 0.0,
    'snow_cm': 0.0,
    'humidity': 89,
    'cloud': 81,
    'feelslike_c': 9.6,
    'feelslike_f': 49.3,
    'windchill_c': 9.6,
    'windchill_f': 49.3,
    'heatindex_c': 9.6,
    'heatindex_f': 49.3,
    'dewpoint_c': 7.9,
    'dewpoint_f': 46.1,
    'will_it_rain': 1,
    'chance_of_rain': 84,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 0.6,
    'gust_kph': 1.0,
    'uv': 2.0},
   {'time_epoch': 1718172000,
    'time': '2024-06-12 07:00',
    'temp_c': 11.2,
    'temp_f': 52.1,
    'is_day': 1,
    'condition': {'text': 'Patchy light drizzle',
     'icon': '//cdn.weatherapi.com/weather/64x64/day/263.png',
     'code': 1150},
    'wind_mph': 1.1,
    'wind_kph': 1.8,
    'wind_degree': 11,
    'wind_dir': 'NNE',
    'pressure_mb': 1022.0,
    'pressure_in': 30.18,
    'precip_mm': 0.22,
    'precip_in': 0.01,
    'snow_cm': 0.0,
    'humidity': 82,
    'cloud': 84,
    'feelslike_c': 11.2,
    'feelslike_f': 52.1,
    'windchill_c': 11.2,
    'windchill_f': 52.1,
    'heatindex_c': 11.2,
    'heatindex_f': 52.1,
    'dewpoint_c': 8.2,
    'dewpoint_f': 46.7,
    'will_it_rain': 1,
    'chance_of_rain': 100,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 5.0,
    'vis_miles': 3.0,
    'gust_mph': 1.4,
    'gust_kph': 2.2,
    'uv': 3.0},
   {'time_epoch': 1718175600,
    'time': '2024-06-12 08:00',
    'temp_c': 12.2,
    'temp_f': 53.9,
    'is_day': 1,
    'condition': {'text': 'Light rain shower',
     'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
     'code': 1240},
    'wind_mph': 0.7,
    'wind_kph': 1.1,
    'wind_degree': 12,
    'wind_dir': 'NNE',
    'pressure_mb': 1022.0,
    'pressure_in': 30.17,
    'precip_mm': 0.59,
    'precip_in': 0.02,
    'snow_cm': 0.0,
    'humidity': 76,
    'cloud': 87,
    'feelslike_c': 12.2,
    'feelslike_f': 53.9,
    'windchill_c': 12.2,
    'windchill_f': 53.9,
    'heatindex_c': 12.2,
    'heatindex_f': 53.9,
    'dewpoint_c': 8.1,
    'dewpoint_f': 46.5,
    'will_it_rain': 1,
    'chance_of_rain': 100,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 0.8,
    'gust_kph': 1.3,
    'uv': 3.0},
   {'time_epoch': 1718179200,
    'time': '2024-06-12 09:00',
    'temp_c': 13.0,
    'temp_f': 55.5,
    'is_day': 1,
    'condition': {'text': 'Light rain shower',
     'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
     'code': 1240},
    'wind_mph': 0.9,
    'wind_kph': 1.4,
    'wind_degree': 246,
    'wind_dir': 'WSW',
    'pressure_mb': 1021.0,
    'pressure_in': 30.16,
    'precip_mm': 0.19,
    'precip_in': 0.01,
    'snow_cm': 0.0,
    'humidity': 69,
    'cloud': 85,
    'feelslike_c': 13.0,
    'feelslike_f': 55.5,
    'windchill_c': 13.0,
    'windchill_f': 55.5,
    'heatindex_c': 13.0,
    'heatindex_f': 55.5,
    'dewpoint_c': 7.6,
    'dewpoint_f': 45.6,
    'will_it_rain': 1,
    'chance_of_rain': 100,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 1.1,
    'gust_kph': 1.8,
    'uv': 3.0},
   {'time_epoch': 1718182800,
    'time': '2024-06-12 10:00',
    'temp_c': 14.4,
    'temp_f': 57.9,
    'is_day': 1,
    'condition': {'text': 'Patchy rain nearby',
     'icon': '//cdn.weatherapi.com/weather/64x64/day/176.png',
     'code': 1063},
    'wind_mph': 2.5,
    'wind_kph': 4.0,
    'wind_degree': 219,
    'wind_dir': 'SW',
    'pressure_mb': 1021.0,
    'pressure_in': 30.16,
    'precip_mm': 0.13,
    'precip_in': 0.0,
    'snow_cm': 0.0,
    'humidity': 61,
    'cloud': 71,
    'feelslike_c': 15.0,
    'feelslike_f': 59.0,
    'windchill_c': 15.0,
    'windchill_f': 59.0,
    'heatindex_c': 14.4,
    'heatindex_f': 57.9,
    'dewpoint_c': 6.9,
    'dewpoint_f': 44.5,
    'will_it_rain': 1,
    'chance_of_rain': 100,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 3.1,
    'gust_kph': 5.0,
    'uv': 3.0},
   {'time_epoch': 1718186400,
    'time': '2024-06-12 11:00',
    'temp_c': 15.5,
    'temp_f': 60.0,
    'is_day': 1,
    'condition': {'text': 'Patchy rain nearby',
     'icon': '//cdn.weatherapi.com/weather/64x64/day/176.png',
     'code': 1063},
    'wind_mph': 3.8,
    'wind_kph': 6.1,
    'wind_degree': 212,
    'wind_dir': 'SSW',
    'pressure_mb': 1021.0,
    'pressure_in': 30.15,
    'precip_mm': 0.11,
    'precip_in': 0.0,
    'snow_cm': 0.0,
    'humidity': 52,
    'cloud': 91,
    'feelslike_c': 15.5,
    'feelslike_f': 60.0,
    'windchill_c': 15.5,
    'windchill_f': 60.0,
    'heatindex_c': 15.5,
    'heatindex_f': 60.0,
    'dewpoint_c': 5.7,
    'dewpoint_f': 42.3,
    'will_it_rain': 1,
    'chance_of_rain': 100,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 4.9,
    'gust_kph': 8.0,
    'uv': 4.0},
   {'time_epoch': 1718190000,
    'time': '2024-06-12 12:00',
    'temp_c': 15.9,
    'temp_f': 60.6,
    'is_day': 1,
    'condition': {'text': 'Patchy rain nearby',
     'icon': '//cdn.weatherapi.com/weather/64x64/day/176.png',
     'code': 1063},
    'wind_mph': 4.5,
    'wind_kph': 7.2,
    'wind_degree': 230,
    'wind_dir': 'SW',
    'pressure_mb': 1021.0,
    'pressure_in': 30.14,
    'precip_mm': 0.06,
    'precip_in': 0.0,
    'snow_cm': 0.0,
    'humidity': 46,
    'cloud': 68,
    'feelslike_c': 15.9,
    'feelslike_f': 60.7,
    'windchill_c': 15.9,
    'windchill_f': 60.7,
    'heatindex_c': 15.9,
    'heatindex_f': 60.7,
    'dewpoint_c': 4.5,
    'dewpoint_f': 40.1,
    'will_it_rain': 1,
    'chance_of_rain': 100,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 5.7,
    'gust_kph': 9.2,
    'uv': 4.0},
   {'time_epoch': 1718193600,
    'time': '2024-06-12 13:00',
    'temp_c': 15.9,
    'temp_f': 60.7,
    'is_day': 1,
    'condition': {'text': 'Patchy rain nearby',
     'icon': '//cdn.weatherapi.com/weather/64x64/day/176.png',
     'code': 1063},
    'wind_mph': 5.6,
    'wind_kph': 9.0,
    'wind_degree': 258,
    'wind_dir': 'WSW',
    'pressure_mb': 1020.0,
    'pressure_in': 30.13,
    'precip_mm': 0.03,
    'precip_in': 0.0,
    'snow_cm': 0.0,
    'humidity': 46,
    'cloud': 100,
    'feelslike_c': 15.9,
    'feelslike_f': 60.7,
    'windchill_c': 15.9,
    'windchill_f': 60.7,
    'heatindex_c': 15.9,
    'heatindex_f': 60.7,
    'dewpoint_c': 4.2,
    'dewpoint_f': 39.6,
    'will_it_rain': 1,
    'chance_of_rain': 84,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 6.6,
    'gust_kph': 10.7,
    'uv': 4.0},
   {'time_epoch': 1718197200,
    'time': '2024-06-12 14:00',
    'temp_c': 15.1,
    'temp_f': 59.2,
    'is_day': 1,
    'condition': {'text': 'Patchy rain nearby',
     'icon': '//cdn.weatherapi.com/weather/64x64/day/176.png',
     'code': 1063},
    'wind_mph': 7.4,
    'wind_kph': 11.9,
    'wind_degree': 262,
    'wind_dir': 'W',
    'pressure_mb': 1020.0,
    'pressure_in': 30.13,
    'precip_mm': 0.04,
    'precip_in': 0.0,
    'snow_cm': 0.0,
    'humidity': 52,
    'cloud': 60,
    'feelslike_c': 15.1,
    'feelslike_f': 59.2,
    'windchill_c': 15.1,
    'windchill_f': 59.2,
    'heatindex_c': 15.1,
    'heatindex_f': 59.2,
    'dewpoint_c': 5.3,
    'dewpoint_f': 41.6,
    'will_it_rain': 1,
    'chance_of_rain': 77,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 9.5,
    'gust_kph': 15.3,
    'uv': 4.0},
   {'time_epoch': 1718200800,
    'time': '2024-06-12 15:00',
    'temp_c': 14.9,
    'temp_f': 58.9,
    'is_day': 1,
    'condition': {'text': 'Patchy rain nearby',
     'icon': '//cdn.weatherapi.com/weather/64x64/day/176.png',
     'code': 1063},
    'wind_mph': 7.4,
    'wind_kph': 11.9,
    'wind_degree': 252,
    'wind_dir': 'WSW',
    'pressure_mb': 1020.0,
    'pressure_in': 30.12,
    'precip_mm': 0.02,
    'precip_in': 0.0,
    'snow_cm': 0.0,
    'humidity': 54,
    'cloud': 57,
    'feelslike_c': 14.3,
    'feelslike_f': 57.7,
    'windchill_c': 14.3,
    'windchill_f': 57.7,
    'heatindex_c': 14.9,
    'heatindex_f': 58.9,
    'dewpoint_c': 5.8,
    'dewpoint_f': 42.4,
    'will_it_rain': 1,
    'chance_of_rain': 72,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 9.5,
    'gust_kph': 15.3,
    'uv': 3.0},
   {'time_epoch': 1718204400,
    'time': '2024-06-12 16:00',
    'temp_c': 15.7,
    'temp_f': 60.3,
    'is_day': 1,
    'condition': {'text': 'Patchy rain nearby',
     'icon': '//cdn.weatherapi.com/weather/64x64/day/176.png',
     'code': 1063},
    'wind_mph': 6.7,
    'wind_kph': 10.8,
    'wind_degree': 262,
    'wind_dir': 'W',
    'pressure_mb': 1020.0,
    'pressure_in': 30.11,
    'precip_mm': 0.03,
    'precip_in': 0.0,
    'snow_cm': 0.0,
    'humidity': 51,
    'cloud': 94,
    'feelslike_c': 15.7,
    'feelslike_f': 60.3,
    'windchill_c': 15.7,
    'windchill_f': 60.3,
    'heatindex_c': 15.7,
    'heatindex_f': 60.3,
    'dewpoint_c': 5.7,
    'dewpoint_f': 42.2,
    'will_it_rain': 1,
    'chance_of_rain': 86,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 8.0,
    'gust_kph': 12.8,
    'uv': 4.0},
   {'time_epoch': 1718208000,
    'time': '2024-06-12 17:00',
    'temp_c': 16.2,
    'temp_f': 61.2,
    'is_day': 1,
    'condition': {'text': 'Sunny',
     'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png',
     'code': 1000},
    'wind_mph': 4.3,
    'wind_kph': 6.8,
    'wind_degree': 280,
    'wind_dir': 'W',
    'pressure_mb': 1019.0,
    'pressure_in': 30.09,
    'precip_mm': 0.02,
    'precip_in': 0.0,
    'snow_cm': 0.0,
    'humidity': 48,
    'cloud': 0,
    'feelslike_c': 15.8,
    'feelslike_f': 60.4,
    'windchill_c': 15.8,
    'windchill_f': 60.4,
    'heatindex_c': 15.8,
    'heatindex_f': 60.4,
    'dewpoint_c': 5.6,
    'dewpoint_f': 42.1,
    'will_it_rain': 1,
    'chance_of_rain': 71,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 8.0,
    'gust_kph': 12.9,
    'uv': 4.0},
   {'time_epoch': 1718211600,
    'time': '2024-06-12 18:00',
    'temp_c': 15.0,
    'temp_f': 59.1,
    'is_day': 1,
    'condition': {'text': 'Patchy rain nearby',
     'icon': '//cdn.weatherapi.com/weather/64x64/day/176.png',
     'code': 1063},
    'wind_mph': 5.4,
    'wind_kph': 8.6,
    'wind_degree': 255,
    'wind_dir': 'WSW',
    'pressure_mb': 1019.0,
    'pressure_in': 30.09,
    'precip_mm': 0.02,
    'precip_in': 0.0,
    'snow_cm': 0.0,
    'humidity': 55,
    'cloud': 100,
    'feelslike_c': 15.0,
    'feelslike_f': 59.1,
    'windchill_c': 15.0,
    'windchill_f': 59.1,
    'heatindex_c': 15.0,
    'heatindex_f': 59.1,
    'dewpoint_c': 6.2,
    'dewpoint_f': 43.2,
    'will_it_rain': 1,
    'chance_of_rain': 87,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 7.4,
    'gust_kph': 11.8,
    'uv': 4.0},
   {'time_epoch': 1718215200,
    'time': '2024-06-12 19:00',
    'temp_c': 14.2,
    'temp_f': 57.5,
    'is_day': 1,
    'condition': {'text': 'Patchy rain nearby',
     'icon': '//cdn.weatherapi.com/weather/64x64/day/176.png',
     'code': 1063},
    'wind_mph': 4.9,
    'wind_kph': 7.9,
    'wind_degree': 257,
    'wind_dir': 'WSW',
    'pressure_mb': 1019.0,
    'pressure_in': 30.1,
    'precip_mm': 0.03,
    'precip_in': 0.0,
    'snow_cm': 0.0,
    'humidity': 62,
    'cloud': 57,
    'feelslike_c': 13.9,
    'feelslike_f': 57.1,
    'windchill_c': 13.9,
    'windchill_f': 57.1,
    'heatindex_c': 14.2,
    'heatindex_f': 57.5,
    'dewpoint_c': 7.0,
    'dewpoint_f': 44.6,
    'will_it_rain': 0,
    'chance_of_rain': 70,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 7.3,
    'gust_kph': 11.7,
    'uv': 3.0},
   {'time_epoch': 1718218800,
    'time': '2024-06-12 20:00',
    'temp_c': 13.2,
    'temp_f': 55.7,
    'is_day': 1,
    'condition': {'text': 'Patchy rain nearby',
     'icon': '//cdn.weatherapi.com/weather/64x64/day/176.png',
     'code': 1063},
    'wind_mph': 4.5,
    'wind_kph': 7.2,
    'wind_degree': 272,
    'wind_dir': 'W',
    'pressure_mb': 1019.0,
    'pressure_in': 30.1,
    'precip_mm': 0.01,
    'precip_in': 0.0,
    'snow_cm': 0.0,
    'humidity': 66,
    'cloud': 88,
    'feelslike_c': 12.9,
    'feelslike_f': 55.2,
    'windchill_c': 12.9,
    'windchill_f': 55.2,
    'heatindex_c': 13.2,
    'heatindex_f': 55.7,
    'dewpoint_c': 7.1,
    'dewpoint_f': 44.7,
    'will_it_rain': 1,
    'chance_of_rain': 80,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 7.2,
    'gust_kph': 11.6,
    'uv': 3.0},
   {'time_epoch': 1718222400,
    'time': '2024-06-12 21:00',
    'temp_c': 12.3,
    'temp_f': 54.1,
    'is_day': 1,
    'condition': {'text': 'Sunny',
     'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png',
     'code': 1000},
    'wind_mph': 3.4,
    'wind_kph': 5.4,
    'wind_degree': 280,
    'wind_dir': 'W',
    'pressure_mb': 1019.0,
    'pressure_in': 30.1,
    'precip_mm': 0.0,
    'precip_in': 0.0,
    'snow_cm': 0.0,
    'humidity': 70,
    'cloud': 24,
    'feelslike_c': 12.2,
    'feelslike_f': 54.0,
    'windchill_c': 12.2,
    'windchill_f': 54.0,

In [33]:
pd.DataFrame(data['forecast']['forecastday'])

,date,date_epoch,day,astro,hour
0,2024-06-12,1718150400,"{'maxtemp_c': 15.9, 'maxtemp_f': 60.7, 'mintem...","{'sunrise': '04:43 AM', 'sunset': '09:18 PM', ...","[{'time_epoch': 1718146800, 'time': '2024-06-1..."
1,2024-06-13,1718236800,"{'maxtemp_c': 15.8, 'maxtemp_f': 60.5, 'mintem...","{'sunrise': '04:43 AM', 'sunset': '09:19 PM', ...","[{'time_epoch': 1718233200, 'time': '2024-06-1..."
2,2024-06-14,1718323200,"{'maxtemp_c': 18.7, 'maxtemp_f': 65.6, 'mintem...","{'sunrise': '04:42 AM', 'sunset': '09:19 PM', ...","[{'time_epoch': 1718319600, 'time': '2024-06-1..."

In [39]:
pd.json_normalize(data['forecast']['forecastday'])

,date,date_epoch,hour,day.maxtemp_c,day.maxtemp_f,day.mintemp_c,day.mintemp_f,day.avgtemp_c,day.avgtemp_f,day.maxwind_mph,...,day.condition.code,day.uv,astro.sunrise,astro.sunset,astro.moonrise,astro.moonset,astro.moon_phase,astro.moon_illumination,astro.is_moon_up,astro.is_sun_up
0,2024-06-12,1718150400,"[{'time_epoch': 1718146800, 'time': '2024-06-1...",15.9,60.7,7.7,45.8,12.3,54.1,7.4,...,1063,3.0,04:43 AM,09:18 PM,10:45 AM,01:03 AM,Waxing Crescent,29,1,0
1,2024-06-13,1718236800,"[{'time_epoch': 1718233200, 'time': '2024-06-1...",15.8,60.5,8.4,47.0,12.2,54.0,14.3,...,1063,4.0,04:43 AM,09:19 PM,11:57 AM,01:15 AM,Waxing Crescent,38,1,0
2,2024-06-14,1718323200,"[{'time_epoch': 1718319600, 'time': '2024-06-1...",18.7,65.6,11.9,53.5,14.6,58.3,15.2,...,1063,6.0,04:42 AM,09:19 PM,01:07 PM,01:26 AM,First Quarter,48,1,0

In [37]:
pd.json_normalize(data['forecast']['forecastday'][0]['hour'])

,time_epoch,time,temp_c,temp_f,is_day,wind_mph,wind_kph,wind_degree,wind_dir,pressure_mb,...,will_it_snow,chance_of_snow,vis_km,vis_miles,gust_mph,gust_kph,uv,condition.text,condition.icon,condition.code
0,1718146800,2024-06-12 00:00,8.7,47.7,0,3.4,5.4,24,NNE,1021.0,...,0,0,10.0,6.0,5.9,9.5,1.0,Overcast,//cdn.weatherapi.com/weather/64x64/night/122.png,1009
1,1718150400,2024-06-12 01:00,8.2,46.8,0,3.1,5.0,31,NNE,1021.0,...,0,0,10.0,6.0,5.5,8.9,1.0,Clear,//cdn.weatherapi.com/weather/64x64/night/113.png,1000
2,1718154000,2024-06-12 02:00,7.9,46.3,0,2.5,4.0,33,NNE,1021.0,...,0,0,10.0,6.0,4.3,6.9,1.0,Clear,//cdn.weatherapi.com/weather/64x64/night/113.png,1000
3,1718157600,2024-06-12 03:00,7.9,46.2,0,1.8,2.9,27,NNE,1021.0,...,0,0,2.0,1.0,3.3,5.3,1.0,Mist,//cdn.weatherapi.com/weather/64x64/night/143.png,1030
4,1718161200,2024-06-12 04:00,7.7,45.8,0,1.6,2.5,32,NNE,1022.0,...,0,0,2.0,1.0,2.9,4.6,1.0,Mist,//cdn.weatherapi.com/weather/64x64/night/143.png,1030
5,1718164800,2024-06-12 05:00,8.5,47.3,1,0.7,1.1,49,NE,1022.0,...,0,0,10.0,6.0,1.1,1.7,3.0,Partly Cloudy,//cdn.weatherapi.com/weather/64x64/day/116.png,1003
6,1718168400,2024-06-12 06:00,9.6,49.3,1,0.4,0.7,354,N,1022.0,...,0,0,10.0,6.0,0.6,1.0,2.0,Patchy rain nearby,//cdn.weatherapi.com/weather/64x64/day/176.png,1063
7,1718172000,2024-06-12 07:00,11.2,52.1,1,1.1,1.8,11,NNE,1022.0,...,0,0,5.0,3.0,1.4,2.2,3.0,Patchy light drizzle,//cdn.weatherapi.com/weather/64x64/day/263.png,1150
8,1718175600,2024-06-12 08:00,12.2,53.9,1,0.7,1.1,12,NNE,1022.0,...,0,0,10.0,6.0,0.8,1.3,3.0,Light rain shower,//cdn.weatherapi.com/weather/64x64/day/353.png,1240
9,1718179200,2024-06-12 09:00,13.0,55.5,1,0.9,1.4,246,WSW,1021.0,...,0,0,10.0,6.0,1.1,1.8,3.0,Light rain shower,//cdn.weatherapi.com/weather/64x64/day/353.png,1240
10,1718182800,2024-06-12 10:00,14.4,57.9,1,2.5,4.0,219,SW,1021.0,...,0,0,10.0,6.0,3.1,5.0,3.0,Patchy rain nearby,//cdn.weatherapi.com/weather/64x64/day/176.png,1063
11,1718186400,2024-06-12 11:00,15.5,60.0,1,3.8,6.1,212,SSW,1021.0,...,0,0,10.0,6.0,4.9,8.0,4.0,Patchy rain nearby,//cdn.weatherapi.com/weather/64x64/day/176.png,1063
12,1718190000,2024-06-12 12:00,15.9,60.6,1,4.5,7.2,230,SW,1021.0,...,0,0,10.0,6.0,5.7,9.2,4.0,Patchy rain nearby,//cdn.weatherapi.com/weather/64x64/day/176.png,1063
13,1718193600,2024-06-12 13:00,15.9,60.7,1,5.6,9.0,258,WSW,1020.0,...,0,0,10.0,6.0,6.6,10.7,4.0,Patchy rain nearby,//cdn.weatherapi.com/weather/64x64/day/176.png,1063
14,1718197200,2024-06-12 14:00,15.1,59.2,1,7.4,11.9,262,W,1020.0,...,0,0,10.0,6.0,9.5,15.3,4.0,Patchy rain nearby,//cdn.weatherapi.com/weather/64x64/day/176.png,1063
15,1718200800,2024-06-12 15:00,14.9,58.9,1,7.4,11.9,252,WSW,1020.0,...,0,0,10.0,6.0,9.5,15.3,3.0,Patchy rain nearby,//cdn.weatherapi.com/weather/64x64/day/176.png,1063
16,1718204400,2024-06-12 16:00,15.7,60.3,1,6.7,10.8,262,W,1020.0,...,0,0,10.0,6.0,8.0,12.8,4.0,Patchy rain nearby,//cdn.weatherapi.com/weather/64x64/day/176.png,1063
17,1718208000,2024-06-12 17:00,16.2,61.2,1,4.3,6.8,280,W,1019.0,...,0,0,10.0,6.0,8.0,12.9,4.0,Sunny,//cdn.weatherapi.com/weather/64x64/day/113.png,1000
18,1718211600,2024-06-12 18:00,15.0,59.1,1,5.4,8.6,255,WSW,1019.0,...,0,0,10.0,6.0,7.4,11.8,4.0,Patchy rain nearby,//cdn.weatherapi.com/weather/64x64/day/176.png,1063
19,1718215200,2024-06-12 19:00,14.2,57.5,1,4.9,7.9,257,WSW,1019.0,...,0,0,10.0,6.0,7.3,11.7,3.0,Patchy rain nearby,//cdn.weatherapi.com/weather/64x64/day/176.png,1063
20,1718218800,2024-06-12 20:00,13.2,55.7,1,4.5,7.2,272,W,1019.0,...,0,0,10.0,6.0,7.2,11.6,3.0,Patchy rain nearby,//cdn.weatherapi.com/weather/64x64/day/176.png,1063
21,1718222400,2024-06-12 21:00,12.3,54.1,1,3.4,5.4,280,W,1019.0,...,0,0,10.0,6.0,5.7,9.1,4.0,Sunny,//cdn.weatherapi.com/weather/64x64/day/113.png,1000
22,1718226000,2024-06-12 22:00,11.0,51.7,0,2.9,4.7,253,WSW,1019.0,...,0,0,10.0,6.0,5.4,8.7,1.0,Clear,//cdn.weatherapi.com/weather/64x64/night/113.png,1000
23,1718229600,2024-06-12 23:00,10.4,50.7,0,3.6,5.8,230,SW,1019.0,...,0,0,10.0,6.0,6.7,10.8,1.0,Clear,//cdn.weatherapi.com/weather/64x64/night/113.png,1000